# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('muted_types', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='members.membership')),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('member_joined', 'Nouveau membre'), ('member_left', 'Membre parti'), ('role_assigned', 'Role attribue'), ('session_reminder', 'Rappel de seance'), ('session_created', 'Nouvelle seance'), ('session_cancelled', 'Seance annulee'), ('beneficiary_selected', 'Beneficiaire designe'), ('contribution_due', 'Cotisation due'), ('contribution_received', 'Cotisation recue'), ('loan_approved', 'Pret approuve'), ('loan_rejected', 'Pret refuse'), ('loan_due', 'Remboursement du'), ('loan_overdue', 'Pret en retard'), ('sanction_applied', 'Sanction appliquee'), ('sanction_waived', 'Sanction graciee'), ('election_started', 'Election ouverte'), ('election_result', 'Resultat election'), ('document_published', 'Document publie'), ('event_created', 'Nouvel evenement'), ('event_reminder', 'Rappel evenement'), ('new_message', 'Nouveau message'), ('trial_expiring', 'Trial expire bientot'), ('subscription_expired', 'Abonnement expire'), ('custom', 'Personnalise')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push notification')], default='in_app', max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoye'), ('delivered', 'Delivre'), ('failed', 'Echoue')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.membership')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['association', 'recipient', 'is_read'], name='notificatio_associa_1dcb64_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx')],
            },
        ),
    ]
