# Generated by Django 5.1.5 on 2026-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('member_joined', 'Nouveau membre'), ('member_left', 'Membre parti'), ('role_assigned', 'Role attribue'), ('session_reminder', 'Rappel de seance'), ('session_created', 'Nouvelle seance'), ('session_cancelled', 'Seance annulee'), ('beneficiary_selected', 'Beneficiaire designe'), ('contribution_due', 'Cotisation due'), ('contribution_received', 'Cotisation recue'), ('loan_approved', 'Pret approuve'), ('loan_rejected', 'Pret refuse'), ('loan_due', 'Remboursement du'), ('loan_overdue', 'Pret en retard'), ('sanction_applied', 'Sanction appliquee'), ('sanction_waived', 'Sanction graciee'), ('election_started', 'Election ouverte'), ('election_result', 'Resultat election'), ('document_published', 'Document publie'), ('event_created', 'Nouvel evenement'), ('event_reminder', 'Rappel evenement'), ('new_message', 'Nouveau message'), ('trial_expiring', 'Trial expire bientot'), ('trial_ended_recommendation', 'Fin de trial avec reco'), ('subscription_expired', 'Abonnement expire'), ('subscription_renewal_pending', 'Renouvellement a confirmer'), ('subscription_tier_recommended', 'Plan recommande'), ('custom', 'Personnalise')], max_length=30),
        ),
    ]
