# Generated by Django 5.1.5 on 2026-04-21 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('charter', 'Charte'), ('bylaws', 'Statuts'), ('internal_rules', 'Reglement interieur'), ('amendment', 'Amendement'), ('other', 'Autre')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Contenu en Markdown ou HTML')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='governance/documents/')),
            ],
            options={
                'db_table': 'governance_documents',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('secret', 'Vote a bulletin secret'), ('open', 'Vote a main levee'), ('consensus', 'Consensus'), ('designation', 'Designation par les statuts'), ('other', 'Autre')], default='secret', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planifiee'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], default='planned', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('is_elected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'election_candidates',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
