# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0002_initial'),
        ('governance', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membership'),
        ),
        migrations.AddField(
            model_name='document',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='election',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='election',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='election',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.session'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='governance.election'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='members.membership'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.bureauposition'),
        ),
        migrations.AddField(
            model_name='vote',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.electioncandidate'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_cast', to='members.membership'),
        ),
        migrations.AlterUniqueTogether(
            name='electioncandidate',
            unique_together={('election', 'membership', 'position')},
        ),
    ]
