# Generated by Django 5.1.5 on 2026-05-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('governance', '0003_announcement_announcementreadstatus'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_associa_53ab91_idx',
            old_name='announcemen_assoc_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_associa_d4c23e_idx',
            old_name='announcemen_assoc_prio_idx',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='announcementreadstatus',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
    ]
