# Generated by Django 5.1.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('governance', '0005_polls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poll',
            new_name='polls_associa_ab9131_idx',
            old_name='poll_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='poll_votes_poll_id_fe2bc6_idx',
            old_name='pollvote_poll_voter_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='poll_votes_poll_id_44e22e_idx',
            old_name='pollvote_poll_fp_idx',
        ),
        migrations.AlterField(
            model_name='poll',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
    ]
