# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'bureau_positions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('expelled', 'Exclu'), ('resigned', 'Démissionnaire')], default='pending', max_length=20)),
                ('cni_number', models.CharField(blank=True, max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Champs personnalisés: profession, quartier, parrain_id, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='BureauMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation_method', models.CharField(blank=True, help_text='fondateur, vote, nomination, statuts', max_length=50)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_members', to='cycles.cycle')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='members.bureauposition')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_positions', to='members.membership')),
            ],
            options={
                'db_table': 'bureau_members',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text='["members.view", "finance.collect", "tontine.manage"] Wildcards: "*", "finance.*"')),
                ('is_bureau_role', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False, help_text='Non supprimable, non modifiable')),
                ('hierarchy_level', models.PositiveIntegerField(default=0, help_text='0 = plus élevé')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to='members.membership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.role')),
            ],
            options={
                'db_table': 'member_roles',
            },
        ),
        migrations.AddField(
            model_name='bureauposition',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.role'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['association', 'status'], name='memberships_associa_31e4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['association', 'is_active'], name='memberships_associa_eeeddc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('association', 'user')},
        ),
        migrations.AddIndex(
            model_name='bureaumember',
            index=models.Index(fields=['association', 'cycle', 'is_active'], name='bureau_memb_associa_a613f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('association', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('membership', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='bureauposition',
            unique_together={('association', 'slug')},
        ),
    ]
