# Generated by Django 5.1.5 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0005_sessionreport_sessionreportattachment'),
        ('members', '0002_membershiprequest_resignation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershiprequest',
            new_name='membership__associa_c82e99_idx',
            old_name='memb_req_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiprequest',
            new_name='membership__user_id_c1f728_idx',
            old_name='memb_req_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='resignation',
            new_name='resignation_associa_d4e0a0_idx',
            old_name='resig_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='resignation',
            new_name='resignation_members_e13941_idx',
            old_name='resig_memb_status_idx',
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text="Cycle pour lequel l'utilisateur souhaite adhérer (optionnel).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_requests', to='cycles.cycle'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
    ]
