# Generated by Django 5.1.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('cycles', '0009_rename_ben_payout_receipt_hash_idx_beneficiary_receipt_a4e646_idx_and_more'),
        ('members', '0007_membership_fee_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipfeepayment',
            name='unique_lifetime_fund_per_membership',
        ),
        migrations.RemoveConstraint(
            model_name='membershipfeepayment',
            name='unique_fund_per_cycle_per_membership',
        ),
        migrations.RenameIndex(
            model_name='memberimportbatch',
            new_name='member_impo_associa_15a51d_idx',
            old_name='mib_assoc_created_idx',
        ),
        migrations.RenameIndex(
            model_name='memberimportrow',
            new_name='member_impo_batch_i_0dcd9d_idx',
            old_name='mir_batch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipfeepayment',
            new_name='membership__associa_35c953_idx',
            old_name='mfp_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipfeepayment',
            new_name='membership__members_2a9590_idx',
            old_name='mfp_member_type_idx',
        ),
        migrations.AlterField(
            model_name='memberimportbatch',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='memberimportrow',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='membershipfeeinstallment',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='membershipfeepayment',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddConstraint(
            model_name='membershipfeepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle__isnull', True), ('fee_type', 'membership_fund')), fields=('membership', 'fee_type'), name='unique_lifetime_fund_per_membership'),
        ),
        migrations.AddConstraint(
            model_name='membershipfeepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle__isnull', False), ('fee_type', 'membership_fund')), fields=('membership', 'fee_type', 'cycle'), name='unique_fund_per_cycle_per_membership'),
        ),
    ]
