# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fixed_amount', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'sanction_types',
                'unique_together': {('association', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payee'), ('waived', 'Graciee'), ('contested', 'Contestee')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_applied', to='members.membership')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='members.membership')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.session')),
                ('sanction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='sanctions.sanctiontype')),
            ],
            options={
                'db_table': 'sanctions',
                'indexes': [models.Index(fields=['association', 'membership', 'status'], name='sanctions_associa_a9df05_idx')],
            },
        ),
    ]
