# Generated by Django 5.1.5 on 2026-05-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0002_sanction_receipt_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sanction',
            new_name='sanctions_receipt_a6c88c_idx',
            old_name='sanction_receipt_hash_idx',
        ),
    ]
