# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
        ('cycles', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_created', to='members.membership'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='linked_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to='members.membership'),
        ),
        migrations.AddField(
            model_name='message',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='members.membership'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['association', '-last_message_at'], name='conversatio_associa_80afa0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['association', 'conv_type'], name='conversatio_associa_a98c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'membership')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
    ]
