# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TontineType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rate_mode', models.CharField(choices=[('fixed', 'Taux unique (fixe)'), ('range', 'Taux variable (min/max)'), ('free', 'Montant libre')], default='range', max_length=20)),
                ('fixed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='XAF', max_length=5)),
                ('allows_multiple_shares', models.BooleanField(default=True)),
                ('max_shares_per_member', models.PositiveIntegerField(default=5)),
                ('share_unit_name', models.CharField(default='nom', help_text='Appellation locale: nom, bouche, main...', max_length=50)),
                ('has_beneficiary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'tontine_types',
                'ordering': ['display_order'],
                'unique_together': {('association', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_shares', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='cycles.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.membership')),
                ('tontine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tontines.tontinetype')),
            ],
            options={
                'db_table': 'member_subscriptions',
                'unique_together': {('membership', 'tontine_type', 'cycle')},
            },
        ),
    ]
