# Generated by Django 5.1.5 on 2026-04-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proxy',
            new_name='proxies_associa_84543a_idx',
            old_name='proxy_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='proxy',
            new_name='proxies_session_d03bf6_idx',
            old_name='proxy_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='proxy',
            new_name='proxies_princip_d37666_idx',
            old_name='proxy_principal_status_idx',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='signed_document',
            field=models.FileField(blank=True, help_text='Procuration signée scannée.', null=True, upload_to='proxies/documents/'),
        ),
    ]
