# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='members.membership'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='resulting_membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_invitation', to='members.membership'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.role'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['association', 'status'], name='invitations_associa_9d9d51_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status'], name='invitations_email_fc68a2_idx'),
        ),
    ]
