# Generated by Django 5.1.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_triple_approval'),
        ('core', '0002_association_created_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bureauapprovalrequest',
            new_name='bureau_appr_associa_f5c634_idx',
            old_name='ba_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bureauapprovalrequest',
            new_name='bureau_appr_associa_6008f1_idx',
            old_name='ba_assoc_action_idx',
        ),
        migrations.RenameIndex(
            model_name='bureauapprovalrequest',
            new_name='bureau_appr_target__7067a5_idx',
            old_name='ba_target_idx',
        ),
        migrations.AlterField(
            model_name='bureauapprovalrequest',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
    ]
