# Generated by Django 5.1.5 on 2026-04-29 12:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallets_associa_9b7432_idx',
            old_name='wallets_assoc_balance_idx',
        ),
        migrations.RenameIndex(
            model_name='walletentry',
            new_name='wallet_entr_wallet__790e7f_idx',
            old_name='wallet_entry_wal_recent_idx',
        ),
        migrations.RenameIndex(
            model_name='walletentry',
            new_name='wallet_entr_associa_dab610_idx',
            old_name='wallet_entry_assoc_src_idx',
        ),
        migrations.RenameIndex(
            model_name='walletentry',
            new_name='wallet_entr_session_7dd00d_idx',
            old_name='wallet_entry_sess_src_idx',
        ),
        migrations.RenameIndex(
            model_name='walletentry',
            new_name='wallet_entr_distrib_8d0573_idx',
            old_name='wallet_entry_batch_idx',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='distribution_batch',
            field=models.UUIDField(blank=True, db_index=True, help_text="Regroupe les WalletEntry issues d'une même distribution.", null=True),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='source_id',
            field=models.UUIDField(blank=True, help_text="Référence (UUID) à l'objet source : AuctionBid, Sanction, LoanRepayment, Contribution, Transaction. Pas de FK pour rester souple.", null=True),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='total_distributed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant brut de la source avant division.', max_digits=14),
        ),
    ]
