# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=5)),
                ('max_members', models.PositiveIntegerField(default=15)),
                ('max_tontine_types', models.PositiveIntegerField(default=2)),
                ('max_cycles', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(default=dict)),
                ('trial_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', "Periode d'essai"), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('cancelled', 'Annule'), ('expired', 'Expire'), ('suspended', 'Suspendu')], default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=20)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('payment_provider_data', models.JSONField(blank=True, default=dict)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.association')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complete'), ('failed', 'Echoue'), ('refunded', 'Rembourse')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money (MTN/Orange)'), ('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Especes')], default='mobile_money', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trial_end'], name='subscriptio_trial_e_d3fa80_idx'),
        ),
    ]
