# Generated by Django 5.1.5 on 2026-04-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_cycles',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_tontine_types',
        ),
        migrations.AddField(
            model_name='plan',
            name='max_monthly_cagnotte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cagnotte mensuelle maximale autorisee (0 = illimite).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_members',
            field=models.PositiveIntegerField(default=15, help_text='0 = illimite'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
