# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryPayout',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guarantor_cni_number', models.CharField(blank=True, help_text='CNI du garant (si différent du membre)', max_length=100, null=True)),
                ('guarantor_signature', models.CharField(blank=True, help_text='Signature du garant (peut être une URL vers une image ou une signature électronique)', max_length=255, null=True)),
                ('confirmation_receipt', models.CharField(blank=True, help_text='Référence du reçu de paiement (numéro de transaction, etc.)', max_length=255, null=True)),
                ('shares_claimed', models.PositiveIntegerField(help_text='Nombre de noms que le bénéficiaire choisit de prendre')),
                ('shares_total', models.PositiveIntegerField(help_text='Nombre total de noms du membre (pour référence)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant effectivement versé au bénéficiaire', max_digits=14)),
                ('acquisition_method', models.CharField(choices=[('scheduled', 'Ordre programmé (tirage/tour de rôle)'), ('auction', 'Enchère (plus offrant)'), ('vote', 'Vote des membres'), ('need', 'Besoin (décision du bureau)'), ('manual', 'Attribution manuelle')], default='scheduled', max_length=20)),
                ('payout_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque')], default='cash', max_length=20, null=True)),
                ('schedule_order', models.PositiveIntegerField(blank=True, help_text="Position dans l'ordre de passage du cycle", null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de versement'), ('paid', 'Versé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beneficiary_payouts',
                'ordering': ['pot__session__date', 'schedule_order'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiarySchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Programme'), ('completed', 'Boucle'), ('skipped', 'Saute'), ('swapped', 'Echange')], default='scheduled', max_length=20)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'beneficiary_schedule',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='draft', max_length=20)),
                ('session_frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bimensuel'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('custom', 'Personnalise')], default='monthly', max_length=20)),
                ('default_session_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_session_time', models.TimeField(blank=True, null=True)),
                ('default_session_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleTontineConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_method', models.CharField(choices=[('random', 'Tirage aleatoire'), ('sequential', 'Tour de role'), ('auction', 'Enchere (plus offrant)'), ('vote', 'Vote des membres'), ('need_based', 'Selon le besoin (decision bureau)'), ('manual', 'Attribution manuelle')], default='random', help_text='Methode appliquee par defaut a chaque seance du cycle', max_length=20)),
                ('allow_override', models.BooleanField(default=False, help_text='Permet au bureau de changer la methode pour une seance specifique')),
                ('allowed_overrides', models.JSONField(blank=True, default=list, help_text='Methodes autorisees en override. Ex: ["auction", "need_based"]')),
                ('auction_premium_destination', models.CharField(choices=[('treasury', 'Caisse de réserve'), ('next_pot', 'Réinjecté dans les prochaines cagnettes'), ('split', 'Partagé entre caisse et cagnotte')], default='treasury', help_text="Où va la prime d'enchère du gagnant", max_length=20)),
                ('auction_premium_split_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='Si split : ratio pour la cagnotte (0.5 = 50%)', max_digits=3)),
                ('config', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "exclude_already_benefited": true,\n            "allow_partial_claim": true,\n            "min_claim_shares": 1,\n            "max_beneficiaries_per_session": null,\n            "allow_carry_over": true,\n            "min_attendance_rate": 0.75,\n            "grace_period_sessions": 2, \n            "reinject_auction_premium": false\n        }\n    ')),
            ],
            options={
                'db_table': 'cycle_tontine_configs',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Programmee'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('cancelled', 'Annulee'), ('postponed', 'Reportee')], default='scheduled', max_length=20)),
                ('minutes', models.TextField(blank=True, help_text='Proces-verbal')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excuse'), ('late', 'En retard'), ('represented', 'Represente')], default='absent', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'session_attendances',
            },
        ),
        migrations.CreateModel(
            name='SessionPot',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, help_text='Somme des cotisations effectivement payées cette session', max_digits=14)),
                ('carry_over_in', models.DecimalField(decimal_places=2, default=0, help_text='Report reçu de la session précédente', max_digits=14)),
                ('auction_premium_in', models.DecimalField(decimal_places=2, default=0, help_text="Prime d'enchère réinjectée (si config le prévoit)", max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distributed', models.DecimalField(decimal_places=2, default=0, help_text='Somme effectivement versée aux bénéficiaires', max_digits=14)),
                ('remainder', models.DecimalField(decimal_places=2, default=0, help_text='Reliquat à reporter à la session suivante', max_digits=14)),
                ('is_closed', models.BooleanField(default=False, help_text='True = distribution terminée, reliquat calculé')),
                ('effective_method', models.CharField(blank=True, choices=[('random', 'Tirage aleatoire'), ('sequential', 'Tour de role'), ('auction', 'Enchere (plus offrant)'), ('vote', 'Vote des membres'), ('need_based', 'Selon le besoin (decision bureau)'), ('manual', 'Attribution manuelle')], default='', help_text='Methode utilisee pour cette seance (heritee ou overridee)', max_length=20)),
                ('is_method_overridden', models.BooleanField(default=False, help_text='True si la methode a ete changee par rapport a la config du cycle')),
                ('override_reason', models.TextField(blank=True, help_text='Justification si la methode a ete overridee')),
            ],
            options={
                'db_table': 'session_pots',
                'ordering': ['session__date'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text="Montant de l'enchère proposée par le membre", max_digits=14)),
                ('status', models.CharField(choices=[('active', 'En cours'), ('won', 'Remportée'), ('lost', 'Perdue'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'auction_bids',
                'ordering': ['-bid_amount'],
            },
        ),
    ]
