# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='members.membership'),
        ),
        migrations.AddField(
            model_name='beneficiarypayout',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='beneficiarypayout',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_payouts', to='members.membership'),
        ),
        migrations.AddField(
            model_name='beneficiarypayout',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontine_payouts', to='members.membership'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='resulting_payout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_auction', to='cycles.beneficiarypayout'),
        ),
        migrations.AddField(
            model_name='beneficiaryschedule',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='beneficiaryschedule',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_slots', to='members.membership'),
        ),
    ]
