# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0002_initial'),
        ('members', '0001_initial'),
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryschedule',
            name='tontine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontinetype'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='beneficiaryschedule',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_schedule', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='cycletontineconfig',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='cycletontineconfig',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontine_configs', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='cycletontineconfig',
            name='tontine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontinetype'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='tontine_types',
            field=models.ManyToManyField(related_name='cycles', through='cycles.CycleTontineConfig', to='tontines.tontinetype'),
        ),
        migrations.AddField(
            model_name='session',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='session',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='beneficiaryschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.membership'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='represented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to='members.membership'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='sessionpot',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='sessionpot',
            name='previous_pot',
            field=models.ForeignKey(blank=True, help_text='Pot de la session précédente (source du carry_over_in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_pot', to='cycles.sessionpot'),
        ),
        migrations.AddField(
            model_name='sessionpot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='sessionpot',
            name='tontine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontinetype'),
        ),
        migrations.AddField(
            model_name='beneficiarypayout',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='cycles.sessionpot'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='cycles.sessionpot'),
        ),
        migrations.AlterUniqueTogether(
            name='cycletontineconfig',
            unique_together={('cycle', 'tontine_type')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('cycle', 'session_number')},
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaryschedule',
            unique_together={('cycle', 'tontine_type', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'membership')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionpot',
            unique_together={('session', 'tontine_type')},
        ),
        migrations.AddIndex(
            model_name='beneficiarypayout',
            index=models.Index(fields=['association', 'membership', 'status'], name='beneficiary_associa_d1d0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['pot', 'status', '-bid_amount'], name='auction_bid_pot_id_aff979_idx'),
        ),
    ]
