# Generated by Django 5.1.5 on 2026-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0008_payout_in_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='beneficiarypayout',
            new_name='beneficiary_receipt_a4e646_idx',
            old_name='ben_payout_receipt_hash_idx',
        ),
        migrations.AlterField(
            model_name='beneficiarypayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant effectivement versé au bénéficiaire (en XAF équivalent si en nature).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='default_session_location',
            field=models.CharField(blank=True, help_text='Adresse par défaut (souvent le siège social).', max_length=255),
        ),
    ]
