# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('disbursed', 'Decaisse'), ('repaying', 'En remboursement'), ('repaid', 'Rembourse'), ('defaulted', 'En defaut')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'loan_repayments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('contribution', 'Cotisation'), ('loan_out', 'Decaissement pret'), ('loan_repayment', 'Remboursement pret'), ('sanction', 'Amende/Sanction'), ('expense', 'Depense'), ('income', 'Revenu divers'), ('beneficiary_payout', 'Versement beneficiaire'), ('adjustment', 'Ajustement')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_debit', models.BooleanField(help_text='True=sortie, False=entree')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('cash', 'Caisse'), ('bank', 'Banque'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], default='cash', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'treasury_accounts',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_shares', models.PositiveIntegerField(default=1)),
                ('rate_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Paye'), ('partial', 'Partiel'), ('defaulted', 'Impaye')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('contribution_justification', models.FileField(blank=True, null=True, upload_to='contribution_justifications/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association')),
            ],
            options={
                'db_table': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
