# Generated by Django 5.1.5 on 2026-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cycles', '0003_initial'),
        ('finance', '0002_initial'),
        ('members', '0001_initial'),
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='tontine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontinetype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to='members.membership'),
        ),
        migrations.AddField(
            model_name='loan',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='guaranteed_loans', to='members.membership'),
        ),
        migrations.AddField(
            model_name='loan',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.membership'),
        ),
        migrations.AddField(
            model_name='loan',
            name='session_granted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_granted', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='cycles.session'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membership'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_recorded', to='members.membership'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.session'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.treasuryaccount'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['association', 'session', 'status'], name='contributio_associa_78a236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('session', 'membership', 'tontine_type')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['association', 'status'], name='loans_associa_eb30cb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['association', 'membership', 'status'], name='loans_associa_3ef614_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['association', 'transaction_type', 'created_at'], name='transaction_associa_ecf056_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['association', 'account', 'created_at'], name='transaction_associa_487690_idx'),
        ),
    ]
