# Generated by Django 5.1.5 on 2026-05-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_tontine_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_associa_b4a289_idx',
            old_name='tx_assoc_tt_created_idx',
        ),
    ]
