# Generated by Django 5.1.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_created_by'),
        ('finance', '0009_transaction_in_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contributioncorrectionrequest',
            new_name='contributio_associa_85be3d_idx',
            old_name='ccr_assoc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contributioncorrectionrequest',
            new_name='contributio_contrib_78a0d9_idx',
            old_name='ccr_contrib_status_idx',
        ),
        migrations.AlterField(
            model_name='contributioncorrectionrequest',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.association'),
        ),
    ]
